version: 2.1
jobs:
  checkout:
    executor: python/default
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  updatePoetryLock:
    executor: python/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Upate Poetry lock file with new dependencies
          command: |
            poetry update
      - persist_to_workspace:
            root: .
            paths:
                - .
  build:
    executor: python/default
    steps:
      - attach_workspace:
          at: .
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
              ./cc-test-reporter before-build
      - run:
          command: |
            mkdir test-results
            poetry run coverage run -m pytest --junitxml=test-results/junit.xml
          name: Test it
      - store_test_results:
          path: test-results
      - run:
          name: Upload coverage to code climate
          command: |
            poetry run coverage xml
            ./cc-test-reporter after-build
orbs:
  python: circleci/python@1.0.0
workflows:
  version: 2
  updateDeps:
    jobs:
      - checkout:
          filters:
            branches:
              only: /^dependabot.*/
      - updatePoetryLock:
          requires:
            - checkout
      - build:
          requires:
            - updatePoetryLock
  main:
    jobs:
      - checkout:
          filters:
            branches:
              ignore: /^dependabot.*/
      - build:
          requires:
            - checkout
