# .github/workflows/coverage.yml
---
name: Coverage
on: push
jobs:
    coverage:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - uses: FedericoCarboni/setup-ffmpeg@v1
            - uses: actions/setup-python@v1
              with:
                  python-version: '3.11'
                  architecture: x64
            - run: pip install nox==2022.11.21
            - run: nox --sessions tests-3.11 examples-3.11
              env:
                  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
