# .github/workflows/coverage.yml
---
name: Coverage
on: push
jobs:
    coverage:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: FedericoCarboni/setup-ffmpeg@v1
            - uses: actions/setup-python@v1
              with:
                  python-version: '3.9'
                  architecture: x64
            - run: pip install nox==2022.11.21
            - run: pip install nox-poetry==1.0.2
            - run: pip install poetry==1.3.2
            - run: nox --sessions tests-3.9 examples-3.9 coverage
              env:
                  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
