# .github/workflows/coverage.yml
---
name: Coverage
on: push
jobs:
    coverage:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: FedericoCarboni/setup-ffmpeg@v1
            - uses: actions/setup-python@v1
              with:
                  python-version: '3.8'
                  architecture: x64
            - run: pip install nox==2021.10.1
            - run: pip install nox-poetry==0.8.4
            - run: pip install poetry==1.1.11
            - run: nox --sessions tests-3.8 examples-3.8 coverage
              env:
                  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
