# .github/workflows/release.yml
name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    name: Build & Publish
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.11'
        architecture: x64
    - name: Install FFMpeg
      uses: FedericoCarboni/setup-ffmpeg@v1
    - name: Build
      run: |
        pip install ".[build]"
        nox -s build-3.11
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
