name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - run: pip install nox==2020.12.31
    - run: pip install poetry==1.1.4
    - run: pip install nox-poetry==0.7.1
    - run: nox
