---
name: Tests
on: push
jobs:
    tests:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: FedericoCarboni/setup-ffmpeg@v1
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.10"
                  architecture: x64
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.9
                  architecture: x64
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8
                  architecture: x64
            - run: pip install nox==2021.10.1
            - run: pip install poetry==1.1.11
            - run: pip install nox-poetry==0.8.6
            - run: nox
