---
name: Tests
on: push
jobs:
    tests:
        strategy:
            fail-fast: false
            matrix:
                os-version:
                    - "ubuntu-20.04"
                python-version:
                    - "3.8"
                    - "3.9"
                experimental:
                    - false
                include:
                    - python-version: "3.8"
                      os-version: "windows-2019"
                      experimental: true
                    - python-version: "3.10"
                      os-version: "ubuntu-20.04"
                      experimental: true
        continue-on-error: ${{ matrix.experimental }}
        runs-on: ${{ matrix.os-version }}
        steps:
            - uses: actions/checkout@v2
            - uses: FedericoCarboni/setup-ffmpeg@v1
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
                  architecture: x64
            - run: pip install nox==2021.10.1
            - run: pip install poetry==1.1.11
            - run: pip install nox-poetry==0.8.6
            - run: nox -s tests-${{ matrix.python-version }} examples-${{ matrix.python-version }}
